<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container29syjor\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container29syjor/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container29syjor.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container29syjor\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container29syjor\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '29syjor',
    'container.build_id' => 'ee5c9afe',
    'container.build_time' => 1597253598,
], __DIR__.\DIRECTORY_SEPARATOR.'Container29syjor');
