<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQQqrFUT\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQQqrFUT/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQQqrFUT.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQQqrFUT\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerQQqrFUT\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'QQqrFUT',
    'container.build_id' => 'cae95041',
    'container.build_time' => 1596999706,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQQqrFUT');
