<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerIPSltxL\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerIPSltxL/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerIPSltxL.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerIPSltxL\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerIPSltxL\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'IPSltxL',
    'container.build_id' => '943a638c',
    'container.build_time' => 1596323007,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerIPSltxL');
